let ACTIONS  = {};

ACTIONS.SET_FILTER = "SET-FITLER";
ACTIONS.SET_PAGE = "SET-PAGE";
ACTIONS.SET_NUMBER_OF_PAGE = "SET-NUMBER-OF-PAGE";

ACTIONS.SET_NUMBER_OF_RESULT = "SET-NUMBER-OF-RESULT";

ACTIONS.REQUEST_MOVIES = "REQUEST-MOVIES";
ACTIONS.RECEIVE_MOVIES = "RECEIVE-MOVIES"; 
ACTIONS.REQUEST_MOVIES_FAILED = "REQUEST-MOVIES-FAILED";




export default ACTIONS; 